main: "${PACKAGE}.SimpleRtp"
name: "${NAME}"
version: "${VERSION}"
loader: "${PACKAGE}.RtpLoader"
api-version: "1.21"
author: winlogon
description: Teleport to a random place, safely
folia-supported: true
permissions:
  simplertp.rtp:
    default: true
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
